/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportPreviewRouteImport } from './routes/report.preview'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicGetReportRouteImport } from './routes/api/public/get-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportPreviewRoute = ReportPreviewRouteImport.update({
  id: '/report/preview',
  path: '/report/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetReportRoute = ApiPublicGetReportRouteImport.update({
  id: '/api/public/get-report',
  path: '/api/public/get-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report/$token': typeof ReportTokenRoute
  '/report/preview': typeof ReportPreviewRoute
  '/api/public/get-report': typeof ApiPublicGetReportRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report/$token': typeof ReportTokenRoute
  '/report/preview': typeof ReportPreviewRoute
  '/api/public/get-report': typeof ApiPublicGetReportRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report/$token': typeof ReportTokenRoute
  '/report/preview': typeof ReportPreviewRoute
  '/api/public/get-report': typeof ApiPublicGetReportRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report/$token'
    | '/report/preview'
    | '/api/public/get-report'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report/$token'
    | '/report/preview'
    | '/api/public/get-report'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/report/$token'
    | '/report/preview'
    | '/api/public/get-report'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ReportPreviewRoute: typeof ReportPreviewRoute
  ApiPublicGetReportRoute: typeof ApiPublicGetReportRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/preview': {
      id: '/report/preview'
      path: '/report/preview'
      fullPath: '/report/preview'
      preLoaderRoute: typeof ReportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-report': {
      id: '/api/public/get-report'
      path: '/api/public/get-report'
      fullPath: '/api/public/get-report'
      preLoaderRoute: typeof ApiPublicGetReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportTokenRoute: ReportTokenRoute,
  ReportPreviewRoute: ReportPreviewRoute,
  ApiPublicGetReportRoute: ApiPublicGetReportRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
